export const SESSIONSLIST = [
  {
    startTime: "3:30 PM",
    location: "HIL Lanier J",
    endTime: "4:30 PM",
    isSelected: 1,
    audienceLevel: "All",
    track: "Career",
    hasConflict: 0,
    startDate: "Thursday, September 27, 2018",
    description: "Blockchain is said to revolutionize the world and break the barriers. Yet today, people of varied genders, ethnicities, educational and socioeconomic backgrounds are underrepresented. This panel will educate the audience on the technology and four Blockchain experts, will discuss what has already been delivered and what still needs to be changed to improve inclusion and diversity.",
    id: 251,
    speakers: "Alexandra Prodromos, Artiona Bogo, Dev Bharel, Hanna Zubko, Marta Piekarska",
    name: "CR110: Fulfilling the Broken Promise of Internet with Diversity in Mind"
  },
  {
    startTime: "12:00 PM",
    location: "MMQ Texan Ballroom D",
    endTime: "1:00 PM",
    isSelected: 0,
    audienceLevel: "Senior/Executive",
    track: "Career",
    hasConflict: 0,
    startDate: "Thursday, September 27, 2018",
    description: "Picture an entrepreneur. Does a white male Mark Zuckerberg type come to mind? While women have shown their strength in the startup world for a long time, female founders are still the exception, not the norm. What gives? This panel will debate what is causing this disparity - pipeline vs. culture, attitudes of men and women, the struggle for financing - and provide strategies to overcome the famine.",
    id: 187,
    speakers: "Mar Hershenson, Marci Meingast, Kate Brodock, Sydney Thomas, Maya Tobias",
    name: "CR402: The Female Founder Famine: Where are the Women Entrepreneurs?"
  },
  {
    location: "GRB 351C",
    isSelected: 0,
    track: "Interactive Media",
    name: "IM653: Game On: An Optimization Toolkit for Real-Time Graphics",
    startTime: "10:00 AM",
    endTime: "10:20 AM",
    audienceLevel: "Intermediate Tech",
    focusArea: "Streaming Media and Life Experiences",
    hasConflict: 0,
    startDate: "Thursday, September 27, 2018",
    description: "Performance is essential to fast, exciting game play on any platform. Come learn the tools of the trade used in the trenches, from Windows tools to built-in Unity and Unreal Engine profilers to Intel's GPA. Let's make fast, fantastic games!",
    id: 154,
    speakers: "Kelly Gawne"
  },
  {
    startTime: "11:00 AM",
    location: "HIL Meeting Room 340",
    endTime: "6:00 PM",
    isSelected: 1,
    audienceLevel: "Faculty",
    hasConflict: 1,
    startDate: "Wednesday, September 26, 2018",
    description: "The Faculty Lounge is a place for faculty and academic staff to informally network, catch up on work, and grab a snack or drink. The Faculty Lounge will be open throughout the conference where faculty and any other attendees with an Academic registration can come relax and take a break.",
    id: 7,
    name: "Faculty Lounge"
  },
  {
    startTime: "4:45 PM",
    location: "GRB 371C",
    endTime: "5:45 PM",
    isSelected: 0,
    audienceLevel: "Beginner Tech",
    track: "Open Source",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "Becoming involved in a humanitarian free and open source software (HFOSS) project provides a wealth of learning opportunities for both students and faculty. However, choosing the right project can be daunting. Learning how to evaluate a project to determine viability for contribution is the first step. This workshop highlights various attributes to consider when selecting an HFOSS project.",
    id: 115,
    speakers: "Emily M. Lovell, Lori Postner, Darci Burdge",
    name: "OS541: Evaluating HFOSS Projects for Student Contribution (Repeat)"
  },
  {
    startTime: "9:00 AM",
    location: "GRB Exhibit Hall A",
    endTime: "11:30 AM",
    isSelected: 1,
    audienceLevel: "All",
    hasConflict: 0,
    startDate: "Friday, September 28, 2018",
    description: "Learn about the innovative technology the next generation is dreaming up on the following topics: Interactive Media, Machine Learning, Natural Language Processing and Software Engineering.",
    id: 286,
    speakers: "Shraddha Piparia, Shreya Sharma, Sharon Levy, Anandi Dutta, Haiman Tian, Azalia Mirhoseini, Zarana Parekh, Rafia Rahim, Meera Haridasa, Judy Hanwen Shen, Veena Gurumurthy, Tao Wang, Corina Florescu, Jessica Loeb, Neda Rohani, Manika Kapoor, Mehrnoosh Shafiee, Zahra Shakeri, Itika Gupta, Mitra Bokaei Hosseini, Jocelyn Lu, Tahsina Farah Sanam, Ashka Shah, Samira Pouyanfar, Tanjila Ahmed, Rakshmi Bhatia, Jeevjyot Singh Chhabda, Nikita Goel",
    name: "Poster Session 5"
  },
  {
    startTime: "12:35 PM",
    location: "HIL Ballroom of Americas D",
    endTime: "12:55 PM",
    isSelected: 0,
    audienceLevel: "Early Career",
    track: "Career",
    hasConflict: 0,
    startDate: "Friday, September 28, 2018",
    description: "Have you ever felt like a fraud in your profession, despite your accomplishments? Success should build confidence, not shake it, but many women and underrepresented minorities in the tech industry struggle with impostor syndrome. Explore and develop actionable strategies to overcome it, learn how self-talk shapes perceptions of worth and build a network to help you \"fake it till you make it.\"",
    id: 361,
    speakers: "Dena Haritos Tsamitis",
    name: "CR213: Fraud Alert: Shatter Impostor Syndrome"
  },
  {
    location: "GRB 320C",
    isSelected: 0,
    track: "Interactive Media",
    name: "IM528: Simulating Life: Autonomy in The Sims",
    startTime: "1:40 PM",
    endTime: "2:00 PM",
    audienceLevel: "Beginner Tech",
    focusArea: "Hands On Interactive Media",
    hasConflict: 0,
    startDate: "Friday, September 28, 2018",
    description: "How do we make a game about life? In this talk, we dig into how we use simple data structures as our building blocks in our autonomy system to create human-like behavior in The Sims. Moreover, we will explore what makes The Sims - a game seemingly about doing chores - a unique and fun experience for the players.",
    id: 380,
    speakers: "Bo Xian See"
  },
  {
    location: "GRB 342C",
    isSelected: 0,
    track: "Computer Systems Engineering",
    name: "CE504: An Introduction to Cloud Native World",
    startTime: "5:00 PM",
    endTime: "5:20 PM",
    audienceLevel: "Beginner Tech",
    focusArea: "System Management",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "Cloud native application (CNA) paradigm can prove to be the key for making an application's lifecycle faster with more modular development, better architecture and more robust and efficient CICD pipelines. This presentation aims to introduce basics of CNA stack, that includes Docker, Kubernetes, role of cloud providers, and challenges involved in making production ready cloud native applications.",
    id: 117,
    speakers: "Prashima Sharma"
  },
  {
    startTime: "1:00 PM",
    location: "MMQ Texan Ballroom E",
    endTime: "2:00 PM",
    isSelected: 0,
    audienceLevel: "Senior/Executive",
    track: "Career",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "We negotiate a variety of issues and items every day. How do you get what you need without burning bridges? We think of negotiations as \"win or lose\", yet lasting success requires a different approach. Whether you are negotiating project scope, client contacts, or your next promotion - how can you negotiate confidently and effectively? Learn practical techniques you can immediately apply.",
    id: 47,
    speakers: "Jodie Stewart, Ching Valdezco",
    name: "CR405: Six Steps to Successful Negotiations"
  },
  {
    startTime: "4:30 PM",
    location: "HIL Lanier B",
    endTime: "5:30 PM",
    isSelected: 0,
    audienceLevel: "Early Career",
    track: "Career",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "Do you feel like you're bragging when you talk about your skills and accomplishments? Do you worry you don't have enough to offer when networking professionally? These are difficult issues all professional women face. If you can self promote authentically, networking and career discussions become easy. Join this session to learn how to identify the ways in which you are awesome and to communicate it while staying true to yourself.",
    id: 108,
    speakers: "Irene Ryabaya, Julia Genina",
    name: "CR201: The Art of Self-Promotion: How to Beat the Bragging Taboo (Repeat)"
  },
  {
    startTime: "4:00 PM",
    location: "HIL Ballroom of Americas C",
    endTime: "5:30 PM",
    isSelected: 0,
    audienceLevel: "All",
    track: "Lunches and Receptions",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "Reception for Latinas in Computing Community. Promote and support Latina technologists from industry, government, and academia. This reception gives Latinas a chance to network with one another, connect with strong role models, and celebrate their accomplishments.",
    id: 98,
    name: "Latinas in Technical Roles Reception"
  },
  {
    location: "GRB 320C",
    isSelected: 1,
    track: "Products A to Z",
    name: "AZ669: So Many Features, So Little Time",
    startTime: "3:15 PM",
    endTime: "4:15 PM",
    audienceLevel: "Intermediate Tech",
    focusArea: "Conceptualization",
    hasConflict: 1,
    startDate: "Wednesday, September 26, 2018",
    description: "What does it take to deliver product features in a timely manner? In project management, it's not an easy feat to balance resources, time, and money, with your customers' needs and happiness. In this workshop, participants will learn what it's like to be part of a product team. Your team will prioritize features against development constraints and create a contingency plan when obstacles arise!",
    id: 85,
    speakers: "Eunice Yang, Kieu Tran, Daniel Rutledge"
  },
  {
    location: "GRB General Assembly C",
    isSelected: 0,
    track: "Artificial Intelligence",
    name: "AI612: Neuromorphic Computing: When Hardware Met AI",
    startTime: "3:40 PM",
    endTime: "4:00 PM",
    audienceLevel: "Intermediate Tech",
    focusArea: "Research Topics in AI",
    hasConflict: 0,
    startDate: "Wednesday, September 26, 2018",
    description: "The next big wave in AI will likely come in the form of custom hardware implementations of neural networks or neuromorphic computers. This presentation will provide an introduction to neuromorphic computing (NC), a perspective on the research questions and current results associated with NC and reflect on the opportunities for NC to revolutionize what we think of as AI and computing as a whole.",
    id: 95,
    speakers: "Catherine Schuman"
  }
];
